volumes:
  redis-data:

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 2s
  server:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_AUTH_TOKEN: ${DATABASE_AUTH_TOKEN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      KV_STORE: ioredis
      REDIS_URL: redis://redis:6379
      POLAR_ENVIRONMENT: ${POLAR_ENVIRONMENT}
      POLAR_ACCESS_TOKEN: ${POLAR_ACCESS_TOKEN}
      POLAR_WEBHOOK_SECRET: ${POLAR_WEBHOOK_SECRET}
      POLAR_STANDARD_SMALL_QUOTA_MONTHLY_PRODUCT_ID: ${POLAR_STANDARD_SMALL_QUOTA_MONTHLY_PRODUCT_ID}
      POLAR_STANDARD_SMALL_QUOTA_ANNUAL_PRODUCT_ID: ${POLAR_STANDARD_SMALL_QUOTA_ANNUAL_PRODUCT_ID}
      POLAR_STANDARD_MEDIUM_QUOTA_MONTHLY_PRODUCT_ID: ${POLAR_STANDARD_MEDIUM_QUOTA_MONTHLY_PRODUCT_ID}
      POLAR_STANDARD_MEDIUM_QUOTA_ANNUAL_PRODUCT_ID: ${POLAR_STANDARD_MEDIUM_QUOTA_ANNUAL_PRODUCT_ID}
      POLAR_STANDARD_LARGE_QUOTA_MONTHLY_PRODUCT_ID: ${POLAR_STANDARD_LARGE_QUOTA_MONTHLY_PRODUCT_ID}
      POLAR_STANDARD_LARGE_QUOTA_ANNUAL_PRODUCT_ID: ${POLAR_STANDARD_LARGE_QUOTA_ANNUAL_PRODUCT_ID}
      POLAR_PRO_MONTHLY_PRODUCT_ID: ${POLAR_PRO_MONTHLY_PRODUCT_ID}
      POLAR_PRO_ANNUAL_PRODUCT_ID: ${POLAR_PRO_ANNUAL_PRODUCT_ID}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      RESEND_API_KEY: ${RESEND_API_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      INSTAPAPER_OAUTH_ID: ${INSTAPAPER_OAUTH_ID}
      INSTAPAPER_OAUTH_SECRET: ${INSTAPAPER_OAUTH_SECRET}
      VITE_PUBLIC_IS_MAIN_INSTANCE: "true"
      VITE_PUBLIC_BASE_URL: ${VITE_PUBLIC_BASE_URL}
      VITE_PUBLIC_SUPPORT_EMAIL_ADDRESS: ${VITE_PUBLIC_SUPPORT_EMAIL_ADDRESS}
      VITE_PUBLIC_IS_MAINTENANCE_MODE: ${VITE_PUBLIC_IS_MAINTENANCE_MODE}
      VITE_PUBLIC_IS_DEMO_INSTANCE: ${VITE_PUBLIC_IS_DEMO_INSTANCE}
    depends_on:
      redis:
        condition: service_healthy
        required: true
    ports:
      - 3000:3000
