/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WelcomeRouteImport } from './app/welcome'
import { Route as SitemapRouteImport } from './app/sitemap'
import { Route as PricingRouteImport } from './app/pricing'
import { Route as MaintenanceRouteImport } from './app/maintenance'
import { Route as AuthRouteImport } from './app/auth'
import { Route as WebRouteImport } from './app/_web'
import { Route as AppRouteImport } from './app/_app'
import { Route as AppIndexRouteImport } from './app/_app.index'
import { Route as AuthVerifyEmailRouteImport } from './app/auth.verify-email'
import { Route as AuthSignUpRouteImport } from './app/auth.sign-up'
import { Route as AuthSignInRouteImport } from './app/auth.sign-in'
import { Route as AuthResetRouteImport } from './app/auth.reset'
import { Route as ApiHealthRouteImport } from './app/api/health'
import { Route as WebGuidesRouteImport } from './app/_web.guides'
import { Route as AppViewsRouteImport } from './app/_app.views'
import { Route as AppTagsRouteImport } from './app/_app.tags'
import { Route as AppImportRouteImport } from './app/_app.import'
import { Route as AppFeedsRouteImport } from './app/_app.feeds'
import { Route as AppDebugRouteImport } from './app/_app.debug'
import { Route as DotwellKnownSiteDotstandardDotpublicationRouteImport } from './app/[.]well-known.site[.]standard[.]publication'
import { Route as WebReleasesIndexRouteImport } from './app/_web.releases.index'
import { Route as WebGuidesIndexRouteImport } from './app/_web.guides.index'
import { Route as AppAdminIndexRouteImport } from './app/_app.admin.index'
import { Route as ApiRpcSplatRouteImport } from './app/api/rpc.$'
import { Route as ApiDemoProvisionRouteImport } from './app/api.demo.provision'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth.$'
import { Route as WebReleasesSlugRouteImport } from './app/_web.releases.$slug'
import { Route as WebGuidesSlugRouteImport } from './app/_web.guides.$slug'
import { Route as AppWatchIdRouteImport } from './app/_app.watch.$id'
import { Route as AppReadIdRouteImport } from './app/_app.read.$id'
import { Route as AppAdminUsersRouteImport } from './app/_app.admin.users'
import { Route as AppAdminStatsRouteImport } from './app/_app.admin.stats'
import { Route as AppAdminSettingsRouteImport } from './app/_app.admin.settings'
import { Route as AppAdminInvitesRouteImport } from './app/_app.admin.invites'
import { Route as AppAdminInfoRouteImport } from './app/_app.admin.info'
import { Route as ApiOgReleasesSlugRouteImport } from './app/api/og/releases.$slug'
import { Route as ApiOgGuidesSlugRouteImport } from './app/api/og/guides.$slug'
import { Route as AppAdminUserIdRouteImport } from './app/_app.admin.user.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WebGuidesRoute = WebGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => WebRoute,
} as any)
const AppViewsRoute = AppViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedsRoute = AppFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const DotwellKnownSiteDotstandardDotpublicationRoute =
  DotwellKnownSiteDotstandardDotpublicationRouteImport.update({
    id: '/.well-known/site.standard.publication',
    path: '/.well-known/site.standard.publication',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebReleasesIndexRoute = WebReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => WebRoute,
} as any)
const WebGuidesIndexRoute = WebGuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebGuidesRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoProvisionRoute = ApiDemoProvisionRouteImport.update({
  id: '/api/demo/provision',
  path: '/api/demo/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebReleasesSlugRoute = WebReleasesSlugRouteImport.update({
  id: '/releases/$slug',
  path: '/releases/$slug',
  getParentRoute: () => WebRoute,
} as any)
const WebGuidesSlugRoute = WebGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WebGuidesRoute,
} as any)
const AppWatchIdRoute = AppWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReadIdRoute = AppReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStatsRoute = AppAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInvitesRoute = AppAdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInfoRoute = AppAdminInfoRouteImport.update({
  id: '/admin/info',
  path: '/admin/info',
  getParentRoute: () => AppRoute,
} as any)
const ApiOgReleasesSlugRoute = ApiOgReleasesSlugRouteImport.update({
  id: '/api/og/releases/$slug',
  path: '/api/og/releases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgGuidesSlugRoute = ApiOgGuidesSlugRouteImport.update({
  id: '/api/og/guides/$slug',
  path: '/api/og/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUserIdRoute = AppAdminUserIdRouteImport.update({
  id: '/admin/user/$id',
  path: '/admin/user/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/sitemap': typeof SitemapRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/site.standard.publication': typeof DotwellKnownSiteDotstandardDotpublicationRoute
  '/debug': typeof AppDebugRoute
  '/feeds': typeof AppFeedsRoute
  '/import': typeof AppImportRoute
  '/tags': typeof AppTagsRoute
  '/views': typeof AppViewsRoute
  '/guides': typeof WebGuidesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/info': typeof AppAdminInfoRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/read/$id': typeof AppReadIdRoute
  '/watch/$id': typeof AppWatchIdRoute
  '/guides/$slug': typeof WebGuidesSlugRoute
  '/releases/$slug': typeof WebReleasesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/provision': typeof ApiDemoProvisionRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/guides/': typeof WebGuidesIndexRoute
  '/releases/': typeof WebReleasesIndexRoute
  '/admin/user/$id': typeof AppAdminUserIdRoute
  '/api/og/guides/$slug': typeof ApiOgGuidesSlugRoute
  '/api/og/releases/$slug': typeof ApiOgReleasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/sitemap': typeof SitemapRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/site.standard.publication': typeof DotwellKnownSiteDotstandardDotpublicationRoute
  '/debug': typeof AppDebugRoute
  '/feeds': typeof AppFeedsRoute
  '/import': typeof AppImportRoute
  '/tags': typeof AppTagsRoute
  '/views': typeof AppViewsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/info': typeof AppAdminInfoRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/read/$id': typeof AppReadIdRoute
  '/watch/$id': typeof AppWatchIdRoute
  '/guides/$slug': typeof WebGuidesSlugRoute
  '/releases/$slug': typeof WebReleasesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/provision': typeof ApiDemoProvisionRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/guides': typeof WebGuidesIndexRoute
  '/releases': typeof WebReleasesIndexRoute
  '/admin/user/$id': typeof AppAdminUserIdRoute
  '/api/og/guides/$slug': typeof ApiOgGuidesSlugRoute
  '/api/og/releases/$slug': typeof ApiOgReleasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_web': typeof WebRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/sitemap': typeof SitemapRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/site.standard.publication': typeof DotwellKnownSiteDotstandardDotpublicationRoute
  '/_app/debug': typeof AppDebugRoute
  '/_app/feeds': typeof AppFeedsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/views': typeof AppViewsRoute
  '/_web/guides': typeof WebGuidesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/info': typeof AppAdminInfoRoute
  '/_app/admin/invites': typeof AppAdminInvitesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/stats': typeof AppAdminStatsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/read/$id': typeof AppReadIdRoute
  '/_app/watch/$id': typeof AppWatchIdRoute
  '/_web/guides/$slug': typeof WebGuidesSlugRoute
  '/_web/releases/$slug': typeof WebReleasesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/provision': typeof ApiDemoProvisionRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_web/guides/': typeof WebGuidesIndexRoute
  '/_web/releases/': typeof WebReleasesIndexRoute
  '/_app/admin/user/$id': typeof AppAdminUserIdRoute
  '/api/og/guides/$slug': typeof ApiOgGuidesSlugRoute
  '/api/og/releases/$slug': typeof ApiOgReleasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/maintenance'
    | '/pricing'
    | '/sitemap'
    | '/welcome'
    | '/.well-known/site.standard.publication'
    | '/debug'
    | '/feeds'
    | '/import'
    | '/tags'
    | '/views'
    | '/guides'
    | '/api/health'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/admin/info'
    | '/admin/invites'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/read/$id'
    | '/watch/$id'
    | '/guides/$slug'
    | '/releases/$slug'
    | '/api/auth/$'
    | '/api/demo/provision'
    | '/api/rpc/$'
    | '/admin/'
    | '/guides/'
    | '/releases/'
    | '/admin/user/$id'
    | '/api/og/guides/$slug'
    | '/api/og/releases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/maintenance'
    | '/pricing'
    | '/sitemap'
    | '/welcome'
    | '/.well-known/site.standard.publication'
    | '/debug'
    | '/feeds'
    | '/import'
    | '/tags'
    | '/views'
    | '/api/health'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/admin/info'
    | '/admin/invites'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/read/$id'
    | '/watch/$id'
    | '/guides/$slug'
    | '/releases/$slug'
    | '/api/auth/$'
    | '/api/demo/provision'
    | '/api/rpc/$'
    | '/admin'
    | '/guides'
    | '/releases'
    | '/admin/user/$id'
    | '/api/og/guides/$slug'
    | '/api/og/releases/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_web'
    | '/auth'
    | '/maintenance'
    | '/pricing'
    | '/sitemap'
    | '/welcome'
    | '/.well-known/site.standard.publication'
    | '/_app/debug'
    | '/_app/feeds'
    | '/_app/import'
    | '/_app/tags'
    | '/_app/views'
    | '/_web/guides'
    | '/api/health'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/_app/'
    | '/_app/admin/info'
    | '/_app/admin/invites'
    | '/_app/admin/settings'
    | '/_app/admin/stats'
    | '/_app/admin/users'
    | '/_app/read/$id'
    | '/_app/watch/$id'
    | '/_web/guides/$slug'
    | '/_web/releases/$slug'
    | '/api/auth/$'
    | '/api/demo/provision'
    | '/api/rpc/$'
    | '/_app/admin/'
    | '/_web/guides/'
    | '/_web/releases/'
    | '/_app/admin/user/$id'
    | '/api/og/guides/$slug'
    | '/api/og/releases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WebRoute: typeof WebRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  PricingRoute: typeof PricingRoute
  SitemapRoute: typeof SitemapRoute
  WelcomeRoute: typeof WelcomeRoute
  DotwellKnownSiteDotstandardDotpublicationRoute: typeof DotwellKnownSiteDotstandardDotpublicationRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoProvisionRoute: typeof ApiDemoProvisionRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiOgGuidesSlugRoute: typeof ApiOgGuidesSlugRoute
  ApiOgReleasesSlugRoute: typeof ApiOgReleasesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/guides': {
      id: '/_web/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof WebGuidesRouteImport
      parentRoute: typeof WebRoute
    }
    '/_app/views': {
      id: '/_app/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AppViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feeds': {
      id: '/_app/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof AppFeedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/site.standard.publication': {
      id: '/.well-known/site.standard.publication'
      path: '/.well-known/site.standard.publication'
      fullPath: '/.well-known/site.standard.publication'
      preLoaderRoute: typeof DotwellKnownSiteDotstandardDotpublicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/releases/': {
      id: '/_web/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof WebReleasesIndexRouteImport
      parentRoute: typeof WebRoute
    }
    '/_web/guides/': {
      id: '/_web/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof WebGuidesIndexRouteImport
      parentRoute: typeof WebGuidesRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/provision': {
      id: '/api/demo/provision'
      path: '/api/demo/provision'
      fullPath: '/api/demo/provision'
      preLoaderRoute: typeof ApiDemoProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/releases/$slug': {
      id: '/_web/releases/$slug'
      path: '/releases/$slug'
      fullPath: '/releases/$slug'
      preLoaderRoute: typeof WebReleasesSlugRouteImport
      parentRoute: typeof WebRoute
    }
    '/_web/guides/$slug': {
      id: '/_web/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof WebGuidesSlugRouteImport
      parentRoute: typeof WebGuidesRoute
    }
    '/_app/watch/$id': {
      id: '/_app/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AppWatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/read/$id': {
      id: '/_app/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof AppReadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/stats': {
      id: '/_app/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AppAdminStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/invites': {
      id: '/_app/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AppAdminInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/info': {
      id: '/_app/admin/info'
      path: '/admin/info'
      fullPath: '/admin/info'
      preLoaderRoute: typeof AppAdminInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og/releases/$slug': {
      id: '/api/og/releases/$slug'
      path: '/api/og/releases/$slug'
      fullPath: '/api/og/releases/$slug'
      preLoaderRoute: typeof ApiOgReleasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/guides/$slug': {
      id: '/api/og/guides/$slug'
      path: '/api/og/guides/$slug'
      fullPath: '/api/og/guides/$slug'
      preLoaderRoute: typeof ApiOgGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/user/$id': {
      id: '/_app/admin/user/$id'
      path: '/admin/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof AppAdminUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDebugRoute: typeof AppDebugRoute
  AppFeedsRoute: typeof AppFeedsRoute
  AppImportRoute: typeof AppImportRoute
  AppTagsRoute: typeof AppTagsRoute
  AppViewsRoute: typeof AppViewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminInfoRoute: typeof AppAdminInfoRoute
  AppAdminInvitesRoute: typeof AppAdminInvitesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStatsRoute: typeof AppAdminStatsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppReadIdRoute: typeof AppReadIdRoute
  AppWatchIdRoute: typeof AppWatchIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminUserIdRoute: typeof AppAdminUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDebugRoute: AppDebugRoute,
  AppFeedsRoute: AppFeedsRoute,
  AppImportRoute: AppImportRoute,
  AppTagsRoute: AppTagsRoute,
  AppViewsRoute: AppViewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminInfoRoute: AppAdminInfoRoute,
  AppAdminInvitesRoute: AppAdminInvitesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStatsRoute: AppAdminStatsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppReadIdRoute: AppReadIdRoute,
  AppWatchIdRoute: AppWatchIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminUserIdRoute: AppAdminUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WebGuidesRouteChildren {
  WebGuidesSlugRoute: typeof WebGuidesSlugRoute
  WebGuidesIndexRoute: typeof WebGuidesIndexRoute
}

const WebGuidesRouteChildren: WebGuidesRouteChildren = {
  WebGuidesSlugRoute: WebGuidesSlugRoute,
  WebGuidesIndexRoute: WebGuidesIndexRoute,
}

const WebGuidesRouteWithChildren = WebGuidesRoute._addFileChildren(
  WebGuidesRouteChildren,
)

interface WebRouteChildren {
  WebGuidesRoute: typeof WebGuidesRouteWithChildren
  WebReleasesSlugRoute: typeof WebReleasesSlugRoute
  WebReleasesIndexRoute: typeof WebReleasesIndexRoute
}

const WebRouteChildren: WebRouteChildren = {
  WebGuidesRoute: WebGuidesRouteWithChildren,
  WebReleasesSlugRoute: WebReleasesSlugRoute,
  WebReleasesIndexRoute: WebReleasesIndexRoute,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WebRoute: WebRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  PricingRoute: PricingRoute,
  SitemapRoute: SitemapRoute,
  WelcomeRoute: WelcomeRoute,
  DotwellKnownSiteDotstandardDotpublicationRoute:
    DotwellKnownSiteDotstandardDotpublicationRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoProvisionRoute: ApiDemoProvisionRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiOgGuidesSlugRoute: ApiOgGuidesSlugRoute,
  ApiOgReleasesSlugRoute: ApiOgReleasesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
